#!/bin/bash

# Data Pipeline : Update to Latest Version
echo ..................
echo Data Pipeline : Update to Latest Version
echo ..................
source .env
echo TAG_KAFKA=${TAG_KAFKA}
echo TAG_SEARCHENGINE=${TAG_SEARCHENGINE}
echo TAG_DATAPIPENODES=${TAG_DATAPIPENODES}
echo TAG_METADATA_YOLO=${TAG_METADATA_YOLO}
echo TAG_METADATA_CLIP=${TAG_METADATA_CLIP}
echo TAG_DATA_MINING=${TAG_DATA_MINING}


# Update to latest version
git pull

# Build Kafka Docker
echo ..................
echo Build Kafka Docker
echo ..................
mkdir kafka
cd kafka
if [ -d "kafka-docker" ] 
then
    echo "kafka-docker already cloned. Calling git pull to get latest version"
    cd  kafka-docker
    git pull
else
    echo "kafka-docker not yet cloned."
    git clone https://github.com/wurstmeister/kafka-docker.git 
    cd  kafka-docker
fi
docker build -t zillyf/kafka:${TAG_KAFKA} .
cd ..
cd ..

# Build Search Engine Docker
echo ..................
echo Search Engine Docker
echo ..................
cd searchengine
docker build -t zillyf/searchengine:${TAG_SEARCHENGINE} .
cd ..

# Build Datapipe Nodes Docker
echo ..................
echo Build Datapipe Node Docker
echo ..................
cd nodes
docker build -t zillyf/datapipenodes:${TAG_DATAPIPENODES} .
cd ..

# Build Data Mining Docker
echo ..................
echo Build Data Mining Docker
echo ..................
cd datamining
docker build -t zillyf/datamining:${TAG_DATA_MINING} .
cd ..

# Build Metadata Yolov5
echo ..................
echo Build Metadata Yolov5 Docker
echo ..................
cd metadataextraction/yolov5
docker build -t zillyf/metadata:${TAG_METADATA_YOLO} .
cd ../..

# Build Metadata Clip
echo ..................
echo Build Metadata Clip Docker
echo ..................
cd metadataextraction/clip
docker build -t zillyf/clip-base:${TAG_METADATA_CLIP} .
cd ../..

