version: '3.3'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  searchengine:
    image: zillyf/searchengine:v1.3.2
    depends_on: 
      - mongodb_container
      - kafka
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: rootpassword
      MONGO_DB_SERVER: mongodb_container:27017
      SEARCHENGINE_PORT: 8000
      KAFKA_WAIT_TIME: 20
      KAFKA_SERVER: kafka:9093
      KAFKA_TOPIC_KITTIDATASETREQUEST: send_kitti_dataset_request
    ports:
      - 8000:8000
    volumes:
      - imagethumbnails:/data/imagethumbnails
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    image: zillyf/kafka:v1
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "send_file:1:1,send_kitti_dataset_request:1:1,topic_test:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 10000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  datapipenodes_send_file:
    image: zillyf/datapipenodes:v1.2.3
    command: ["python3", "app/sendFilesConsumer.py"]
    depends_on: 
      - kafka
      - mongodb_container
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: rootpassword
      MONGO_DB_SERVER: mongodb_container:27017
      KAFKA_SERVER: kafka:9093
      KAFKA_TOPIC_SENDFILES: send_file
      PYTHONUNBUFFERED: 1
    volumes:
      - imagethumbnails:/data/imagethumbnails
      - imageblobstorage:/data/imageblobstorage
      - downloads:/data/downloads
      - extractedfiles:/data/extractedfiles
  datapipenodes_kitti_data_request:
    image: zillyf/datapipenodes:v1.2.3
    command: ["python3", "app/sendKittiDatasetRequestConsumer.py"]    
    depends_on: 
      - kafka
    environment:
      KAFKA_SERVER: kafka:9093
      KAFKA_TOPIC_SENDFILES: send_file
      KAFKA_TOPIC_KITTIDATASETREQUEST: send_kitti_dataset_request
      PYTHONUNBUFFERED: 1
    volumes:
      - imagethumbnails:/data/imagethumbnails
      - imageblobstorage:/data/imageblobstorage
      - downloads:/data/downloads
      - extractedfiles:/data/extractedfiles
                
volumes:
  mongodb_data_container:
  imagethumbnails:
  imageblobstorage:
  downloads:
  extractedfiles:
