#!/bin/bash

# convenience script if yo want to get started with changing code, running it separately

#docker pull mongo
pip3 install pymongo
pip3 install fastapi
pip3 install uvicorn
pip3 install kafka-python
