#!/bin/bash

sudo apt-get update

# Install Docker
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

mkdir kafka
cd kafka
git clone https://github.com/wurstmeister/kafka-docker.git 
cd ..

# Jupyter Notebook
#docker pull zillyf/ros-data-science:v1.0.0
#sudo docker run zillyf/ros-data-science:v1.0.0 -p8888:8888

#Web Docker
#docker build -t zillyf/searchengine:v1.0.0 .
