#!/bin/bash

#docker run -d -p 27017-27019:27017-27019 --name mongodb mongo

cd kafka/kafka-docker
docker-compose -f docker-compose-kafka.yml up -d
cd ../..

#docker-compose -f kafka/kafka-docker/docker-compose-kafka.yml up -d
#docker-compose -f kafka/kafka-docker/docker-compose.yml up -d


docker-compose -f docker-compose.yml up 

#sudo docker run zillyf/ros-data-science:v1.0.0 -p8888:8888
#sudo docker run  -p8001:8001 zillyf/searchengine:v1.0.0
